### PR TITLE
yunohost_demo test on stretch

### PR DESCRIPTION
**Pull request by yalh76**
Tested installation of yunohost_demo on stretch/buster but don't have enough memory available to do a full test.

- *added prerequisites in ReadMe*
- *Fix error password is weak https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/utils/password.py*
- *Fix lxc installation on Buster that use [lxc 3.0.0](https://github.com/lxc/lxd/issues/4396#issuecomment-378322166)*
- *Fix ssh first connection host validation*
- *Fix letsencrpt requesting if email can be sent to EFF - Electronix Frontier Fundation*
- *Fix nginx configuration to let  yunohost_demo installed on another url than demo.yunohost.org*

### CODE REVIEW

**Comment by yalh76** [comment]
@maniackcrudelis test of yunohost_demo done

**Review by maniackcrudelis — APPROVED** [review]

**Comment by maniackcrudelis** [comment]
Thanks a lot @yalh76 for your work on this.
Does that mean we can run the upgrade on any new server to deploy a new demo ?

If so, we should ask to remove our current VM and build a new one to deploy a new demo.

**Comment by yalh76** [comment]
> 
> 
> Thanks a lot @yalh76 for your work on this.
> Does that mean we can run the upgrade on any new server to deploy a new demo ?
> 
> If so, we should ask to remove our current VM and build a new one to deploy a new demo.

Yes we can run the upgrade on any new server to deploy a new demo. We can also have many demos. 

In my tests, demo server needs a lot of memory, like more than 8Gb.

With only 8Gb, sometimes during deployment of the demo I had some `out of memory` errors. My tests have been done on hyperV VM with dynamix memory on fresh installed:
- debian-9.9.0-amd64
- debian-buster-DI-rc1-amd64 
And the VM took more than 8Gb of dynamic RAM.

**Comment by maniackcrudelis** [comment]
Why would it needs that much memory !?
Do you know which process or which part of the install needed that much ?

I don't think the current server has 8Gb of RAM.

**Comment by yalh76** [comment]
I can try to check what took so much memory during the demo_lxc_build.sh

Do you know how many memory the actual demo server has?

Just to fix memory to not have HyperV dynamic memory related issue...

**Comment by yalh76** [comment]
After removing dynamic RAM on HyperV, installation works. Tested with a 4 Gb RAM VM

**Comment by maniackcrudelis** [comment]
The current demo server has 4Gb RAM and 1 Gb Swap.

**Comment by yalh76** [comment]
So it will work.
You can ask the demo VM to be rebuilt

**Pull request merged**
